apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.api.internal.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
{{ include "selectorLabels" . | indent 4 }}
