name: push-main

# 1. Run unit and integration tests
# 2. Push containers to AWS ECR with tag based on incrementing build number
# 3. Recommit an update to the chart's deployments with the updated build number in the `deployment` branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up DBs
        run: docker-compose -f docker-compose.db.yml up -d && sleep 30

      - name: Check DBs
        run: make ps

      - name: Run unit tests
        run: cd src && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/coverage.out
          flags: unit
          fail_ci_if_error: true

      - name: Bring up stack
        run: make up && sleep 30

      - name: Check stack
        run: make ps

      - name: Run integration tests
        run: cd tests && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/coverage.out
          flags: integration
          fail_ci_if_error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_WORKER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_WORKER }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr-worker
        uses: aws-actions/amazon-ecr-login@v1

      - name: Worker - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-worker.outputs.registry }}
          ECR_REPOSITORY: icon-transactions-worker
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build --target prod --build-arg SERVICE_NAME=worker -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_API }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_API }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr-api
        uses: aws-actions/amazon-ecr-login@v1

      - name: API - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-api.outputs.registry }}
          ECR_REPOSITORY: icon-transactions-api
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build --target prod --build-arg SERVICE_NAME=api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Merge main -> deployment-dev
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: deployment-dev
          github_token: ${{ github.token }}

      - name: Checkout dev deployment
        uses: actions/checkout@v2
        with:
          ref: deployment-dev
          path: deployment-dev

      - name: Update dev-mainnet deployment values file (API) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-mainnet/values.dev.yaml'
          propertyPath: 'api.image.tag'
          value: ${{ github.run_number }}
          branch: deployment-dev
          createPR: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          commitChange: false
          workDir: deployment-dev

      - name: Update dev-mainnet deployment values file (WORKER) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-mainnet/values.dev.yaml'
          propertyPath: 'worker.image.tag'
          value: ${{ github.run_number }}
          branch: deployment-dev
          createPR: 'false'
          message: 'Update dev deployment (mainnet) image versions to ${{ github.run_number }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          workDir: deployment-dev

      - name: Update dev-sejong deployment values file (API) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-sejong/values.dev.yaml'
          propertyPath: 'api.image.tag'
          value: ${{ github.run_number }}
          branch: deployment-dev
          createPR: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          commitChange: false
          workDir: deployment-dev

      - name: Update dev-sejong deployment values file (WORKER) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-sejong/values.dev.yaml'
          propertyPath: 'worker.image.tag'
          value: ${{ github.run_number }}
          branch: deployment-dev
          createPR: 'false'
          message: 'Update dev deployment (sejong) image versions to ${{ github.run_number }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          workDir: deployment-dev
